#!/usr/bin/env bash
# A script that prints "To infinity and beyond" indefinitely and
# "I am invincible" when receiving a SIGTERM signal


while :
do
	echo "To infinity and beyond"
	trap "echo I am invincible!!!" SIGTERM
	sleep 2
done
