#!/usr/bin/env bash
#if file exist empty
hfile="school"
if [ -e $hfile ] 
then
	echo "school file exists"
	if [ -s $hfile ]
	then
		echo "school file is not empty"
	else
		echo "school file is empty"
	fi

	if [ -f $hfile ]
	then
		echo "school is a regular file"
	fi
else
	echo "school file does not exist"
fi
